### ISSUE TITLE
mashling run mashling gateway is not working in windows

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/vscode-extension-mashling#13]
/ is getting appened in windows at the very beginning.
cd /c:/Users/lmekala/Documents/GoWorkspace/src/github.com/TIBCOSoftware/mashling/examples/recipes/v2
bash: cd: /c:/Users/lmekala/Documents/GoWorkspace/src/github.com/TIBCOSoftware/mashling/examples/recipes/v2: No such file or directory

**Comment by tbhatia1912** [comment]
fixed in #14
